locallender/app/api/urls.py
from django.conf.urls import patterns, url, include

from .api import *

from .api import PostList, PostDetail, UserPostList
from .api import PhotoList, PhotoDetail, PostPhotoList

user_urls = patterns('',
    url(r'^/(?P<username>[0-9a-zA-Z_-]+)/posts$', UserPostList.as_view(), name='userpost-list'),
    url(r'^/(?P<username>[0-9a-zA-Z_-]+)$', UserDetail.as_view(), name='user-detail'),
    url(r'^$', UserList.as_view(), name='user-list')
)
post_urls = patterns('',
    url(r'^/(?P<pk>\d+)/photos$', PostPhotoList.as_view(), name='postphoto-list'),
    url(r'^/(?P<pk>\d+)$', PostDetail.as_view(), name='post-detail'),
    url(r'^$', PostList.as_view(), name='post-list')
)
photo_urls = patterns('',
    url(r'^/(?P<pk>\d+)$', PhotoDetail.as_view(), name='photo-detail'),
    url(r'^$', PhotoList.as_view(), name='photo-list')
)
staff_urls = patterns('',
    url(r'^/(?P<pk>\d+)$', PhotoDetail.as_view(), name='photo-detail'),
    url(r'^$', StaffLogin.as_view(), name='staff-login')
)
customer_urls = patterns('',
    url(r'^/(?P<pk>\d+)$', PhotoDetail.as_view(), name='photo-detail'),
    url(r'^$', CustomerSignUp.as_view(), name='customer-signup')
)
lender_urls = patterns('',
    url(r'^/(?P<pk>\d+)$', PhotoDetail.as_view(), name='photo-detail'),
    url(r'^$', GetLenders.as_view(), name='get-lenders')
)
urlpatterns = patterns('',
    url(r'^users', include(user_urls)),
    url(r'^posts', include(post_urls)),
    url(r'^photos', include(photo_urls)),
    url(r'^staff', include(staff_urls)),
    url(r'^customer', include(customer_urls)),
    url(r'^lendersignup$',LenderSignUp.as_view(), name='lender-signup'),
    url(r'^login',Login.as_view(), name='login'),
    url(r'^forgotpassword',ForgotPassword.as_view(), name='forgot-password'),
    url(r'^signout/$', SignOut.as_view(), name='signout'),
    url(r'^getLenders', include(lender_urls)),
    url(r'^approveLender/$', ApproveLender.as_view(), name='approve-lender'),
    url(r'^getActiveLenders/$', GetActiveLenders.as_view(), name='get-activelender'),
    url(r'^getCustomerInfo$', GetCustomerInfo.as_view(), name='get-customerinfo'),
    url(r'^getCustomers/$', GetCustomers.as_view(), name='get-customers'),
    url(r'^customerexists$',CustomerExistence.as_view(), name='customer-exists'),
    url(r'^mylender',MyLender.as_view(), name='my-lender'),
    url(r'^approveLead/$', ApproveLead.as_view(), name='approve-lead'),
    url(r'^saveLeadInfo$', SaveLeadInfo.as_view(), name='save-leadinfo'),
    url(r'^getMyLeads/$', GetMyLeads.as_view(), name='get-myleads'),
    url(r'^leadStatus/$', ChangeLeadStatus.as_view(), name='change-leadstatus'),
    url(r'^saveLenderInfo/$', SaveLenderInfo.as_view(), name='save-lenderinfo'),
    url(r'^getLenderInfo/$', GetLenderInfo.as_view(), name='get-lenderinfo'),
    #url(r'^lenderRequest/$', LenderRequest.as_view(), name='lender-request'),
  
)

locallender/app/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.views.generic import TemplateView

from app.views import *
from django.contrib.auth.views import login,logout
from django.contrib.auth.decorators import user_passes_test

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
login_forbidden =  user_passes_test(lambda u: u.is_anonymous(), '/dashboard')

class SimpleStaticView(TemplateView):
    def get_template_names(self):
        return [self.kwargs.get('template_name') + ".html"]
    
    def get(self, request, *args, **kwargs):

        from django.contrib.auth import authenticate, login

        #from django.contrib.auth import authenticate, login

        #if request.user.is_anonymous():
            # Auto-login the User for Demonstration Purposes
            #user = authenticate()
            #login(request, user)
        return super(SimpleStaticView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return super(SimpleStaticView, self).get(request, *args, **kwargs)


urlpatterns = patterns('',
    url(r'^api/', include('app.api.urls')),
    url(r'^dashboard/api/', include('app.api.urls')),
    url(r'^customer-dashboard/api/', include('app.api.urls')),
    url(r'^lender-dashboard/api/', include('app.api.urls')),
    url(r'^myaccount/api/', include('app.api.urls')),
    url(r'^mylender/api/', include('app.api.urls')),
    url(r'^leads/api/', include('app.api.urls')),
    url(r'^staffdashboard/api/', include('app.api.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^(?P<template_name>\w+)$', SimpleStaticView.as_view(), name='app'),
    url(r'^$', TemplateView.as_view(template_name='base.html'), name="homepage"),
    url(r'^accounts/register/$', login_forbidden(TemplateView.as_view(template_name='lenders/SignUp.html'))),


    url(r'^lenderSignUp/', TemplateView.as_view(template_name='lenderSignUp.html')),
    url(r'^SignIn/', TemplateView.as_view(template_name='SignIn.html')),

    #url(r'^accounts/register', TemplateView.as_view(template_name='lenderSignUp.html')),
    url(r'^accounts/login/$', login_forbidden(login), name="login"),
    #url(r'^login/', TemplateView.as_view(template_name='login.html')),

    url(r'^forgotPassword/', TemplateView.as_view(template_name='forgotpassword.html')),
    #url(r'^application/', TemplateView.as_view(template_name='static.html')),
    
    #dashboard url's
    url(r'^dashboard/', TemplateView.as_view(template_name='dashboard.html')),
    url(r'^customer-dashboard/', TemplateView.as_view(template_name='customers/dashboard.html')),
    url(r'^lender-dashboard/$', TemplateView.as_view(template_name='lenders/profile.html')),
    url(r'^lender-dashboard/get-started$', TemplateView.as_view(template_name='lenders/dashboard.html')),
    url(r'^staffdashboard/(?P<template_name>\w+)$', SimpleStaticView.as_view(), name='staff'),
    
    
    url(r'^mylender/', TemplateView.as_view(template_name='customers/myLender.html')),
    url(r'^myaccount/', TemplateView.as_view(template_name='customers/profile.html')),
    url(r'^leads/', TemplateView.as_view(template_name='lenders/leads.html')),
    
    url(r'^login/sso/', include('freshdesk.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    # django-registration URLs:
    url(r'^accounts/', include('registration.backends.default.urls')),
    
    url(r'^lender-dashboard/payments/', include('djstripe.urls', namespace="djstripe")),
    url(r'^freshdesk/', include('freshdesk_api.urls')),
    
    #url(r'^notifications/settings/$', include('notifications.urls')),  
    url(r'^avatar/', include('avatar.urls')),
    url(r'staffdashboard/helpdesk/', include('helpdesk.urls')),
)

if settings.DEBUG:
    from django.views.static import serve
    urlpatterns += patterns('',
        url(r'^(?P<path>favicon\..*)$', serve, {'document_root': settings.STATIC_ROOT}),
        url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], serve, {'document_root': settings.MEDIA_ROOT}),
        url(r'^%s(?P<path>.*)$' % settings.STATIC_URL[1:], 'django.contrib.staticfiles.views.serve', dict(insecure=True)),
    )

locallender/app/api/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes import generic

class User(AbstractUser):
	Converted=(
	('0','0'),
	('1','1')
	)
	followers = models.ManyToManyField('self', related_name='followees', symmetrical=False)
	phone_number = models.CharField(max_length=255,blank=True,null=True)
	zip_code = models.PositiveIntegerField(_("zip_code"),blank=True,null=True)
	group = models.CharField(max_length=255)
	entityname = models.CharField(max_length=255)
	state = models.CharField(max_length=255)
	ownerName = models.CharField(max_length=255)
	ownerEmail = models.CharField(max_length=255)
	ownerPhone = models.PositiveIntegerField(_("ownerPhone"))
	storeName = models.CharField(max_length=255)
	storeAddress = models.CharField(max_length=255)
	EinNumber = models.CharField(max_length=255,blank=True,null=True)
	managerName = models.CharField(max_length=255)
	managerEmail = models.CharField(max_length=255)
	managerPhone = models.CharField(max_length=255,blank=True,null=True)
	longitude = models.FloatField()
	latitude = models.FloatField()
	loanLimit =  models.FloatField(null=True)
	city = models.CharField(max_length=255)
	service = models.CharField(max_length=255)
	lead_conversion = models.PositiveIntegerField(_("lead_conversion"),blank=False,null=True,choices=Converted)
	
class UserProfile(models.Model):
    user = models.ForeignKey('api.User')
    avatar = generic.GenericRelation(
        'user_media.UserMediaImage',
    )


class Post(models.Model):
	author = models.ForeignKey(User, related_name='posts')
	title = models.CharField(max_length=255)
	body = models.TextField(blank=True, null=True)


class Photo(models.Model):
	post = models.ForeignKey(Post, related_name='photos')
	image = models.ImageField(upload_to="%Y/%m/%d")

'''Leads model to save lead data'''
class Leads(models.Model):
	Status = (
	(0, 'False'),
	(1, 'True')
	)

	IncomeType = (
	('EMPLOYMENT','EMPLOYMENT'),
	('BENEFITS','BENEFITS'),
	('SELFEMPLOYED','SELFEMPLOYED'),
	('UNEMPLOYED','UNEMPLOYED')
	)
	
	AccountType = (
	('CHECKING','CHECKING'),
	('SAVINGS','SAVINGS')
	)
	
	PayFrequency=(
	('WEEKLY','WEEKLY'),
	('BIWEEKLY','BIWEEKLY'),
	('TWICEMONTH','TWICEMONTH'),
	('MONTHLY','MONTHLY')
	)
	
	States = (
	('ALABAMA','AL'),
	('ALASKA','AK'),
	('ARIZONA','AZ'),
	('ARKANSAS','AR'),
	('CALIFORNIA','CA'),
	('COLORADO','CO'),
	('CONNECTICUT','CT'),
	('DELAWARE','DE'),
	('FLORIDA','FL'),
	('GEORGIA','GA'),
	('HAWAII','HI'),
	('IDAHO','ID'),
	('ILLINOIS','IL'),
	('INDIANA','IN'),
	('IOWA','IA'),
	('KANSAS','KS'),
	('KENTUCKY','KY'),
	('LOUISIANA','LA'),
	('MAINE','ME'),
	('MARYLAND','MD'),
	('MASSACHUSETTS','MA'),
	('MICHIGAN','MI'),
	('MINNESOTA','MN'),
	('MISSISSIPPI','MS'),
	('MISSOURI','MO'),
	('MONTANA','MT'),
	('NEBRASKA','NE'),
	('NEVADA','NV'),
	('NEW HAMPSHIRE','NH'),
	('NEW JERSEY','NJ'),
	('NEW MEXICO','NM'),
	('NEW YORK','NY'),
	('NORTH CAROLINA','NC'),
	('NORTH DAKOTA','ND'),
	('OHIO','OH'),
	('OKLAHOMA','OK'),
	('OREGON','OR'),
	('PENNSYLVANIA','PA'),
	('RHODE ISLAND','RI'),
	('SOUTH CAROLINA','SC'),
	('SOUTH DAKOTA','SD'),
	('TENNESSEE','TN'),
	('TEXAS','TX'),
	('UTAH','UT'),
	('VERMONT','VT'),
	('VIRGINIA','VA'),
	('WASHINGTON','WA'),
	('WEST VIRGINIA','WV'),
	('WISCONSIN','WI'),
	('WYOMING','WY'),
	)
	
	Offered=(
	('0','0'),
	('1','1')
	)

	first_name = models.CharField(max_length=50,blank=False,null=False)
	last_name = models.CharField(max_length=50,blank=False,null=False)
	middle_init = models.CharField(max_length=1,blank=True)
	street_addr1 = models.CharField(max_length=50,blank=False,null=False)
	street_addr2 = models.CharField(max_length=50,blank=True,null=False)
	city = models.CharField(max_length=100,blank=False,null=False)
	state = models.CharField(max_length=2,blank=False,null=False)
	Zip = models.PositiveIntegerField(_("Zip"),blank=False,null=True)
	social_security = models.PositiveIntegerField(_("social_security"),blank=False,null=True)
	phone_home = models.PositiveIntegerField(_("Home_Phone "),blank=False,null=True)
	phone_cell = models.PositiveIntegerField(_("phone_cell "),blank=True,null=True)
	phone_work = models.PositiveIntegerField(_("phone_work "),blank=False,null=True)
	phone_work_ext = models.PositiveIntegerField(_("phone_work_ext "),blank=True,null=True)
	Email = models.EmailField(max_length=50,blank=False,null=False)
	birth_date = models.DateField(blank=False,null=True)
	employer_name = models.CharField(max_length=35,blank=False,null=True)
	pay_frequency = models.CharField(max_length=12,blank=False,null=True,choices=PayFrequency)
	direct_deposit = models.PositiveIntegerField(_("direct_deposite"),blank=False,null=True)
	pay_day1 = models.DateField(blank=False,null=True)
	pay_day2 = models.DateField(blank=False,null=True)
	bank_aba = models.PositiveIntegerField(_("bank_aba"),blank=False,null=True)
	bank_account = models.PositiveIntegerField(_("bank_account"),blank=False,null=True)
	bank_name = models.CharField(max_length=30,blank=False,null=True)
	income_monthly = models.PositiveIntegerField(_("income_monthly"),blank=False,null=True)
	own_home = models.PositiveIntegerField(_("own_home"),blank=False,null=True,choices=Status)
	drivers_license =  models.CharField(max_length=25,blank=False,null=True)
	drivers_license_st = models.CharField(max_length=2,blank=False,null=True)
	client_url_root = models.URLField(max_length=100,blank=False,null=True)
	client_ip_address =  models.IPAddressField(null=True, blank=False, default=None)
	email_alternate = models.EmailField(max_length=100,blank=True,null=True)
	months_employed = models.PositiveIntegerField(_("months_employed"),blank=False,null=True)
	income_type = models.CharField(max_length=15,blank=False,null=True,choices=IncomeType)
	is_military = models.PositiveIntegerField(_("own_home"),blank=False,null=True,choices=Status)
	bank_account_type = models.CharField(max_length=10,blank=False,null=True,choices=AccountType)
	requested_amount = models.PositiveIntegerField(_("requested_amount"),blank=False,null=True)
	months_at_address = models.PositiveIntegerField(_("months_at_address"),blank=False,null=True)
	months_at_bank = models.PositiveIntegerField(_("months_at_bank"),blank=False,null=True)
	source = models.CharField(max_length=10,blank=False,null=True)
	offered = models.PositiveIntegerField(_("offered"),blank=False,null=True,choices=Offered)
	user_id = models.PositiveIntegerField(_("user_id"),blank=False,null=True)
	offered_to = models.PositiveIntegerField(_("offered_to"),blank=False,null=True)
	created_on = models.DateTimeField(blank=False,null=True)
	updated_on = models.DateTimeField(blank=True,null=True)


	

'''Status Codes Model'''
class StatusCodes(models.Model):
	Lead_Status = (
	('101','Have not gone yet'),
	('102','On my way'),
	('103','Got my Loan')
	)
	Lead_Status_Codes = (
	('101','101'),
	('102','102'),
	('103','103')
	)
	name = models.CharField(max_length=100,blank=False,null=False,choices=Lead_Status,db_column='name')
	value = models.PositiveIntegerField(_("value"),blank=False,null=False,choices=Lead_Status_Codes,db_column='value')




'''Lead-Status Model'''
class LeadStatus(models.Model):
	lead_id = models.PositiveIntegerField(_("value"),blank=False,null=True,db_column='lead_id')
	status_id = models.PositiveIntegerField(_("value"),blank=False,null=True,db_column='status_id')
	added_on = models.DateField(blank=False,null=True)
	updated_on = models.DateField(blank=True,null=True)
	


	


	

locallender/app/api/templates/helpdesk/dashboard.html
{% extends "helpdesk/base.html" %}{% load i18n %}{% load url from future %}
{% block helpdesk_title %}{% trans "Helpdesk Dashboard" %}{% endblock %}
{% block helpdesk_head %}
<script type='text/javascript' language='javascript' src='{{ STATIC_URL }}helpdesk/hover.js'></script>
{% endblock %}
{% block helpdesk_body %}

<div class="alert alert-warning">
<p>{% trans "Welcome to your Helpdesk Dashboard! From here you can quickly see tickets submitted by you, tickets you are working on, and those tickets that have no owner." %}</p>
</div>

<table class="table table-hover table-bordered">
<thead>
<tr class='row_tablehead'><td colspan='5'>{% trans "Helpdesk Summary" %}</td></tr>
<tr class='row_columnheads'><th>{% trans "Queue" %}</th><th>{% trans "Open" %}</th><th>{% trans "Resolved" %}</th><th>{% trans "Closed" %}</th></tr>
</thead>
<tbody>
{% for queue in dash_tickets %}
<tr class='row_{% cycle odd,even %} row_hover '>
<th><a href='{% url 'helpdesk_list' %}?queue={{ queue.queue }}&status=1&status=2'>{{ queue.name }}</a></th>
<td align="center">{% if queue.open %}<a href='{% url 'helpdesk_list' %}?queue={{ queue.queue }}&status=1&status=2'>{% endif %}{{ queue.open }}{% if queue.open %}</a>{% endif %}</td>
<td align="center">{% if queue.resolved %}<a href='{% url 'helpdesk_list' %}?queue={{ queue.queue }}&status=3'>{% endif %}{{ queue.resolved }}{% if queue.resolved %}</a>{% endif %}</td>
<td align="center">{% if queue.closed %}<a href='{% url 'helpdesk_list' %}?queue={{ queue.queue }}&status=4'>{% endif %}{{ queue.closed }}{% if queue.closed %}</a>{% endif %}</td>
</tr>
{% endfor %}
</tbody>
</table>




<br style='clear: both;' />

<table class="table table-hover table-bordered">
<thead>
<tr class='row_tablehead' style="color: #fbff00;"><td colspan='2'><i>{% trans "Current Ticket Stats" %}</i></td></tr>
<tr><td colspan='2'>- {% trans "Average number of days until ticket is closed (all tickets): " %}<strong style="color: red;">{{ basic_ticket_stats.average_nbr_days_until_ticket_closed }}</strong>.</td></tr> 
<tr><td colspan='2'>- {% trans "Average number of days until ticket is closed (tickets opened in last 60 days): " %}<strong style="color: red;">{{ basic_ticket_stats.average_nbr_days_until_ticket_closed_last_60_days }}</strong>. 
{% trans "Click" %} <strong><a href="{% url 'helpdesk_report_index' %}daysuntilticketclosedbymonth">here</a></strong> {% trans "for detailed average by month." %} </td></tr>
<tr><td colspan='2'>- {% trans "Distribution of open tickets, grouped by time period:" %}</td></tr>
<tr class='row_columnheads'><th>{% trans "Days since opened" %}</th><th>{% trans "Number of open tickets" %}</th></tr>
</thead>
<tbody>
{% for entry in basic_ticket_stats.open_ticket_stats %}
<tr class='row_{% cycle odd,even %} row_hover'>
<th style="padding-left: 20px;">{{ entry.0 }}</th>
<td style="padding-left: 20px;"><span style="color: {{ entry.2 }};">{% if entry.1 > 0 %}<a href="{% url 'helpdesk_list' %}?{{ entry.3 }}">{{ entry.1 }}</a>{% else %}{{ entry.1 }}{% endif %}</span></td>
</tr>
{% endfor %}
</tbody>
</table>


{% if all_tickets_reported_by_current_user %}
<table class="table table-hover table-bordered">
<thead>
<tr class='row_tablehead'><td colspan='6'>{% trans "All Tickets submitted by you" %}</td></tr>
<tr class='row_columnheads'><th>#</th><th>{% trans "Pr" %}</th><th>{% trans "Title" %}</th><th>{% trans "Queue" %}</th><th>{% trans "Status" %}</th><th>{% trans "Last Update" %}</th></tr>
</thead>
<tbody>
{% for ticket in all_tickets_reported_by_current_user %}
<tr class='row_{% cycle odd,even %} row_hover'>
<th><a href='{{ ticket.get_absolute_url }}'>{{ ticket.ticket }}</a></th>
<td>{{ ticket.get_priority_span }}</td>
<th><a href='{{ ticket.get_absolute_url }}'>{{ ticket.title }}</a></th>
<td>{{ ticket.queue }}</td>
<td>{{ ticket.get_status }}</td>
<td><span title='{{ ticket.modified|date:"r" }}'>{{ ticket.modified|timesince }}</span></td>
</tr>
{% endfor %}
</tbody>
</table>
{% endif %}

<table class="table table-hover table-bordered">
<thead>
<tr class='row_tablehead'><td colspan='6'>{% trans "Open Tickets assigned to you (you are working on this ticket)" %}</td></tr>
<tr class='row_columnheads'><th>#</th><th>{% trans "Pr" %}</th><th>{% trans "Title" %}</th><th>{% trans "Queue" %}</th><th>{% trans "Status" %}</th><th>{% trans "Last Update" %}</th></tr>
</thead>
<tbody>
{% for ticket in user_tickets %}
<tr class='row_{% cycle odd,even %} row_hover'>
<th><a href='{{ ticket.get_absolute_url }}'>{{ ticket.ticket }}</a></th>
<td>{{ ticket.get_priority_span }}</td>
<th><a href='{{ ticket.get_absolute_url }}'>{{ ticket.title }}</a></th>
<td>{{ ticket.queue }}</td>
<td>{{ ticket.get_status }}</td>
<td><span title='{{ ticket.modified|date:"r" }}'>{{ ticket.modified|timesince }}</span></td>
</tr>
{% endfor %}
{% if not user_tickets %}
<tr class='row_odd'><td colspan='6'>{% trans "You have no tickets assigned to you." %}</td></tr>
{% endif %}
</tbody>
</table>

<table class="table table-hover table-bordered">
<thead>
<tr class='row_tablehead'><td colspan='6'>{% trans "Unassigned Tickets" %} {% trans "(pick up a ticket if you start to work on it)" %}</td></tr>
<tr class='row_columnheads'><th>#</th><th>{% trans "Pr" %}</th><th>{% trans "Title" %}</th><th>{% trans "Queue" %}</th><th>{% trans "Created" %}</th><th>&nbsp;</th></tr>
</thead>
<tbody>
{% for ticket in unassigned_tickets %}
<tr class='row_{% cycle odd,even %} row_hover'>
<th><a href='{{ ticket.get_absolute_url }}'>{{ ticket.ticket }}</a></th>
<td>{{ ticket.get_priority_span }}</td>
<th><a href='{{ ticket.get_absolute_url }}'>{{ ticket.title }}</a></th>
<td>{{ ticket.queue }}</td>
<td><span title='{{ ticket.created|date:"r" }}'>{{ ticket.created|timesince }} ago</span></td>
<th><a href='{{ ticket.get_absolute_url }}?take'><span class='button button_take'>{% trans "Take" %}</span></a> | <a href='{% url 'helpdesk_delete' ticket.id %}'><span class='button button_delete'>{% trans "Delete" %}</span></a></th>
</tr>
{% endfor %}
{% if not unassigned_tickets %}
<tr class='row_odd'><td colspan='6'>{% trans "There are no unassigned tickets." %}</td></tr>
{% endif %}
</tbody>
</table>


{% if user_tickets_closed_resolved %}
<table class="table table-hover table-bordered">
<thead>
<tr class='row_tablehead'><td colspan='6'>{% trans "Closed & resolved Tickets you used to work on" %}</td></tr>
<tr class='row_columnheads'><th>#</th><th>{% trans "Pr" %}</th><th>{% trans "Title" %}</th><th>{% trans "Queue" %}</th><th>{% trans "Status" %}</th><th>{% trans "Last Update" %}</th></tr>
</thead>
<tbody>
{% for ticket in user_tickets_closed_resolved %}
<tr class='row_{% cycle odd,even %} row_hover'>
<th><a href='{{ ticket.get_absolute_url }}'>{{ ticket.ticket }}</a></th>
<td>{{ ticket.get_priority_span }}</td>
<th><a href='{{ ticket.get_absolute_url }}'>{{ ticket.title }}</a></th>
<td>{{ ticket.queue }}</td>
<td>{{ ticket.get_status }}</td>
<td><span title='{{ ticket.modified|date:"r" }}'>{{ ticket.modified|timesince }}</span></td>
</tr>
{% endfor %}
</tbody>
</table>
{% endif %}

{% endblock %}

locallender/app/api/templates/helpdesk/email_ignore_add.html
{% extends "helpdesk/base.html" %}{% load i18n %}

{% block helpdesk_title %}{% trans "Ignore E-Mail Address" %}{% endblock %}

{% block helpdesk_body %}{% blocktrans %}
<h2>Ignore E-Mail Address</h2>

<p>To ignore an e-mail address and prevent any emails from that address creating tickets automatically, enter the e-mail address below.</p>

<p>You can either enter a whole e-mail address such as <em>email@domain.com</em> or a portion of an e-mail address with a wildcard, such as <em>*@domain.com</em> or <em>user@*</em>.</p>{% endblocktrans %}

<form method='post' action='./'>

<fieldset>
    <dl>{% for field in form %}
        <dt><label for='id_{{ field.name }}'>{{ field.label }}</label></dt>
        <dd>{{ field }}</dd>
        {% if field.errors %}<dd class='error'>{{ field.errors }}</dd>{% endif %}
        {% if field.help_text %}<dd class='form_help_text'>{{ field.help_text }}</dd>{% endif %}
    {% endfor %}</dl>
</fieldset>

<input class="btn btn-primary" type='submit' value='{% trans "Ignore E-Mail Address" %}' />

{% csrf_token %}</form>

{% endblock %}

locallender/app/api/templates/helpdesk/followup_edit.html
{% extends "helpdesk/base.html" %}{% load i18n %}
{% block helpdesk_title %}{% trans "Edit followup" %}{% endblock %}
{% block helpdesk_head %}{% endblock helpdesk_head %}

{% block helpdesk_body %}

{% include "helpdesk/ticket_desc_table.html" %}

<h3>{% trans "Edit FollowUp" %}</h3>
    <form action="." method="POST" name="edit_followup_form">
        {{ form.non_field_errors }}
        <fieldset>
        <dl>
            <dt><label for='id_ticket'>{% trans "Reassign ticket:" %}</label></dt>
            <dd>{{ form.ticket }}</dd>
            <dt><label for="id_title">{% trans "Title:" %}</label></dt>
            <dd>{{ form.title }}</dd>
            <dt><label for="id_comment">{% trans "Comment:" %}</label></dt>
            <dd>{{ form.comment }}</dd>
            <dt><label for="id_public">Public:</label></dt>
            <dd>{{ form.public }}</dd>
                <p>Public tickets are viewable by the submitter and all staff, but non-public tickets can only be seen by staff.</p>
            <dt><label for="id_new_status">New Status:</label></dt>
            <dd>{{ form.new_status }}</dd>
                <p>If the status was changed, what was it changed to?</p>
        </dl>
        </fieldset>
        <p><input class="btn btn-primary" type="submit" value="Submit"></p>{% csrf_token %}
    </form>
{% endblock helpdesk_body %}